### ISSUE TITLE
不知道为什么gulp之后一直都是这样

### ISSUE THREAD

**Issue by supermanzero** [lmk123/angularjs-requirejs-rjs-md5#2]
E:\git\angularjs-requirejs-rjs-md5>gulp
[15:11:46] Using gulpfile E:\git\angularjs-requirejs-rjs-md5\gulpfile.js
[15:11:46] Starting 'clean'...

**Comment by lmk123** [comment]
你可以将里面的

``` js
function clean (done) {
    del('.js',done);
}
```

改成

``` js
function clean () {
   return del('.js');
}
```

我也会立刻把这个问题改正过来的 ;)

因为 del 模块升级到了 2.x ，替换掉原本的 callback 式写法，改为返回一个 Promise ，但是我的项目里仍然使用 1.x 的语法，所以任务会卡在这里。

**Comment by supermanzero** [comment]
Thx
